# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: de291228237a13f39328da80224ae25dc94b46c673ec32e4f28ab22caa29737f8f5de75d0483963b245eb50e740c7f7f90cc9ff228883cb8697577dc4de1166f

test:
  secret_key_base: 046f0a349a19bee5ee66314a908b303b11eddc6ad3cf4f7b2d5943c4bccfe2bb924397c2ea46bbf15ca24fdc1f5a77d73bf2f0dbd7e1470371f0742d769b08af

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
